import { useState } from "react";
import Footer from "../components/Footer";
import API from "../services/api";

export default function Sell() {
  const [image, setImage] = useState(null); const [preview, setPreview] = useState(null); const [exchange, setExchange] = useState(false);
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [price, setPrice] = useState(""); const [city, setCity] = useState(""); const [condition, setCondition] = useState("");
  const handleImage = (e) => { const file = e.target.files[0]; if (!file) return; setImage(file); setPreview(URL.createObjectURL(file)); };
  const handleSubmit = async () => { try { const formData = new FormData(); formData.append("name", name); formData.append("description", description); formData.append("price", price); formData.append("city", city); formData.append("condition", condition); formData.append("exchange", exchange); formData.append("image", image); const token = localStorage.getItem("token"); const { data } = await API.post("/books", formData, { headers: { Authorization:`Bearer ${token}`, "Content-Type":"multipart/form-data" } }); console.log(data); alert("Book posted successfully!"); } catch (err) { console.log(err.response?.data); alert("Error posting book"); } };
  return <div className="page-shell bg-[#f7faff] text-slate-900"><main className="section-wrap pb-20"><div className="mb-10"><p className="text-sm font-bold uppercase tracking-[.18em] text-blue-600">Create listing</p><h1 className="mt-2 text-4xl font-black tracking-tight sm:text-5xl">Pass your book forward.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500">Add the details someone needs to decide whether your book is the right fit.</p></div>
    <div className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]">
      <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-card"><div className="mb-4"><h2 className="font-bold">Book cover</h2><p className="mt-1 text-xs text-slate-500">Upload an image so buyers can quickly recognise the listing.</p></div><div className="relative flex min-h-[430px] items-center justify-center overflow-hidden rounded-2xl border-2 border-dashed border-blue-200 bg-gradient-to-br from-blue-50 to-slate-50 transition hover:border-blue-400">{preview ? <img src={preview} alt="preview" className="absolute inset-0 h-full w-full object-cover" /> : <div className="text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-white text-2xl text-blue-600 shadow-sm">＋</div><p className="mt-5 font-semibold text-slate-800">Choose a cover image</p><p className="mt-2 text-xs text-slate-400">JPG, PNG or similar image</p></div>}<input type="file" accept="image/*" onChange={handleImage} className="absolute inset-0 cursor-pointer opacity-0" /></div></div>
      <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-card md:p-8"><div className="grid gap-5"><label className="text-sm font-semibold text-slate-700">Book name<input value={name} onChange={(e)=>setName(e.target.value)} placeholder="e.g. Clean Code" className="input-premium mt-2" /></label><label className="text-sm font-semibold text-slate-700">Description<textarea value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="Tell someone about the book's condition and edition..." rows="5" className="input-premium mt-2 resize-none" /></label><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Price<input type="number" value={price} onChange={(e)=>setPrice(e.target.value)} placeholder="₹ 0" className="input-premium mt-2" /></label><label className="text-sm font-semibold text-slate-700">City<input value={city} onChange={(e)=>setCity(e.target.value)} placeholder="Your city" className="input-premium mt-2" /></label></div><label className="text-sm font-semibold text-slate-700">Condition<select value={condition} onChange={(e)=>setCondition(e.target.value)} className="input-premium mt-2"><option value="">Select condition</option><option>Like New</option><option>Good</option><option>Fair</option></select></label><label className="flex cursor-pointer items-center justify-between rounded-2xl border border-blue-100 bg-blue-50/60 p-4"><span><span className="block text-sm font-bold text-slate-800">Available for exchange</span><span className="mt-1 block text-xs text-slate-500">Let someone offer a book instead of a purchase.</span></span><input type="checkbox" checked={exchange} onChange={()=>setExchange(!exchange)} className="h-5 w-5 accent-blue-600" /></label><button onClick={handleSubmit} className="btn-primary mt-2 w-full py-3.5">Publish listing <span>→</span></button></div></div>
    </div></main><Footer /></div>;
}
